package org.example.api.dto.dash;

import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.schabi.newpipe.extractor.MediaFormat;
import org.schabi.newpipe.extractor.stream.SubtitlesStream;

import java.util.Locale;
import java.util.Set;
import java.util.function.Consumer;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/**
 * Unit tests for SubtitleMetadataDTO.
 *
 * <p>Reduced from 20 tests to 11 methods (~24 executions). Validation
 * uses setter mutators (not builder mutators, unlike the sibling DTOs):
 * the full constructor coalesces {@code bandwidth <= 0} to 256, so the
 * zero-bandwidth violation can only be produced by setting it directly
 * on an already-built instance — the original suite did the same thing;
 * this keeps that technique but folds it into the same parameterized
 * table as the blank-string cases. mimeType inference (VTT/SRT/default)
 * and the language-code table are each one parameterized test.</p>
 *
 * <p>Note for the summary: unlike AudioStreamMetadataDTO, which defaults
 * a null locale to "und"/"Unknown", this class defaults to "en"/"English"
 * — worth confirming that asymmetry is intentional.</p>
 */
@DisplayName("SubtitleMetadataDTO Tests")
class SubtitleMetadataDTOTest {

    private Validator validator;
    private ObjectMapper objectMapper;

    @BeforeEach
    void setUp() {
        validator = Validation.buildDefaultValidatorFactory().getValidator();
        objectMapper = new ObjectMapper();
    }

    // ── Helpers ──────────────────────────────────────────────────────────

    private static SubtitleMetadataDTO.Builder validBuilder() {
        return SubtitleMetadataDTO.builder()
                .id("subtitle-1")
                .url("https://example.com/subtitle.vtt")
                .language("en")
                .languageName("English")
                .mimeType("text/vtt")
                .kind("subtitles")
                .bandwidth(256);
    }

    private SubtitlesStream subtitlesStream(Locale locale, String displayName, MediaFormat format,
                                            boolean autoGenerated) {
        SubtitlesStream stream = mock(SubtitlesStream.class);
        when(stream.getContent()).thenReturn("https://example.com/subtitle.vtt");
        when(stream.getLocale()).thenReturn(locale);
        when(stream.getDisplayLanguageName()).thenReturn(displayName);
        when(stream.getFormat()).thenReturn(format);
        when(stream.isAutoGenerated()).thenReturn(autoGenerated);
        return stream;
    }

    // ── Builder ──────────────────────────────────────────────────────────

    @Test
    @DisplayName("Builder wires every field to its own getter")
    void builderWiresAllFields() {
        SubtitleMetadataDTO dto = validBuilder().format("VTT").build();

        assertThat(dto.getId()).isEqualTo("subtitle-1");
        assertThat(dto.getUrl()).isEqualTo("https://example.com/subtitle.vtt");
        assertThat(dto.getLanguage()).isEqualTo("en");
        assertThat(dto.getLanguageName()).isEqualTo("English");
        assertThat(dto.getMimeType()).isEqualTo("text/vtt");
        assertThat(dto.getKind()).isEqualTo("subtitles");
        assertThat(dto.getBandwidth()).isEqualTo(256);
        assertThat(dto.getFormat()).isEqualTo("VTT");
    }

    @Test
    @DisplayName("Defaults bandwidth to 256 via both the no-args constructor and an explicit non-positive value")
    void defaultsBandwidthTo256() {
        assertThat(new SubtitleMetadataDTO().getBandwidth()).isEqualTo(256);
        assertThat(validBuilder().bandwidth(0).build().getBandwidth()).isEqualTo(256);
    }

    // ── Validation ───────────────────────────────────────────────────────

    @Test
    @DisplayName("A fully-populated DTO passes validation")
    void validDtoPassesValidation() {
        assertThat(validator.validate(validBuilder().build())).isEmpty();
    }

    static Stream<Arguments> invalidFieldCases() {
        return Stream.of(
                Arguments.of("blank id", (Consumer<SubtitleMetadataDTO>) d -> d.setId(""),
                        "Subtitle ID cannot be blank"),
                Arguments.of("blank url", (Consumer<SubtitleMetadataDTO>) d -> d.setUrl(""),
                        "Subtitle URL cannot be blank"),
                Arguments.of("blank language", (Consumer<SubtitleMetadataDTO>) d -> d.setLanguage(""),
                        "Subtitle language cannot be blank"),
                Arguments.of("blank mimeType", (Consumer<SubtitleMetadataDTO>) d -> d.setMimeType(""),
                        "Subtitle MIME type cannot be blank"),
                // Only reachable via the setter: the full constructor
                // coalesces bandwidth <= 0 to 256.
                Arguments.of("zero bandwidth (set directly)",
                        (Consumer<SubtitleMetadataDTO>) d -> d.setBandwidth(0),
                        "Bandwidth must be at least 1"));
    }

    @ParameterizedTest(name = "Rejects {0}")
    @MethodSource("invalidFieldCases")
    @DisplayName("Rejects DTOs violating a single constraint, with the matching message")
    void rejectsInvalidField(String name, Consumer<SubtitleMetadataDTO> mutator, String expectedMessage) {
        SubtitleMetadataDTO dto = validBuilder().build();
        mutator.accept(dto);

        Set<ConstraintViolation<SubtitleMetadataDTO>> violations = validator.validate(dto);

        assertThat(violations).isNotEmpty();
        assertThat(violations).anyMatch(v -> v.getMessage().contains(expectedMessage));
    }

    // ── from() ───────────────────────────────────────────────────────────

    @Test
    @DisplayName("Maps id, url, kind, and fixed bandwidth from a fully-populated SubtitlesStream")
    void mapsAllFieldsFromValidStream() {
        SubtitlesStream stream = subtitlesStream(Locale.ENGLISH, "English", MediaFormat.VTT, false);

        SubtitleMetadataDTO dto = SubtitleMetadataDTO.from(stream, 1);

        assertThat(dto.getId()).isEqualTo("subtitle-1");
        assertThat(dto.getUrl()).isEqualTo("https://example.com/subtitle.vtt");
        assertThat(dto.getKind()).isEqualTo("subtitles");
        assertThat(dto.getBandwidth()).isEqualTo(256);
        assertThat(dto.getFormat()).isEqualTo(MediaFormat.VTT.getName());
    }

    @Test
    @DisplayName("Rejects a null SubtitlesStream with IllegalArgumentException")
    void rejectsNullSubtitlesStream() {
        assertThatThrownBy(() -> SubtitleMetadataDTO.from(null, 1))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("SubtitlesStream cannot be null");
    }

    @Test
    @DisplayName("Sets kind to 'asr' for auto-generated subtitles, 'subtitles' otherwise")
    void setsKindFromAutoGeneratedFlag() {
        SubtitleMetadataDTO auto = SubtitleMetadataDTO.from(
                subtitlesStream(Locale.ENGLISH, "English", MediaFormat.VTT, true), 1);
        SubtitleMetadataDTO manual = SubtitleMetadataDTO.from(
                subtitlesStream(Locale.ENGLISH, "English", MediaFormat.VTT, false), 1);

        assertThat(auto.getKind()).isEqualTo("asr");
        assertThat(manual.getKind()).isEqualTo("subtitles");
    }

    static Stream<Arguments> mimeTypeCases() {
        return Stream.of(
                Arguments.of(MediaFormat.VTT, "text/vtt"),
                Arguments.of(MediaFormat.SRT, "application/x-subrip"),
                Arguments.of(null, "application/ttml+xml"));
    }

    @ParameterizedTest(name = "{0} -> {1}")
    @MethodSource("mimeTypeCases")
    @DisplayName("Infers mimeType from format, defaulting to TTML for null or unrecognised formats")
    void infersMimeTypeFromFormat(MediaFormat format, String expectedMimeType) {
        SubtitleMetadataDTO dto = SubtitleMetadataDTO.from(
                subtitlesStream(Locale.ENGLISH, "English", format, false), 1);

        assertThat(dto.getMimeType()).isEqualTo(expectedMimeType);
    }

    static Stream<Arguments> languageCases() {
        return Stream.of(
                Arguments.of("null locale and no display name -> en/English default",
                        null, null, "en", "English"),
                Arguments.of("locale with no display name -> computed name",
                        Locale.forLanguageTag("es"), null, "es", "Spanish"),
                Arguments.of("locale with a provided display name -> display name wins",
                        Locale.FRENCH, "Français (France)", "fr", "Français (France)"));
    }

    @ParameterizedTest(name = "{0}")
    @MethodSource("languageCases")
    @DisplayName("Resolves language from locale and languageName from the display name, falling back to a computed name")
    void resolvesLanguageAndName(String name, Locale locale, String displayName,
                                 String expectedLanguage, String expectedName) {
        SubtitleMetadataDTO dto = SubtitleMetadataDTO.from(
                subtitlesStream(locale, displayName, MediaFormat.VTT, false), 1);

        assertThat(dto.getLanguage()).isEqualTo(expectedLanguage);
        assertThat(dto.getLanguageName()).isEqualTo(expectedName);
    }

    // ── JSON ─────────────────────────────────────────────────────────────

    @Test
    @DisplayName("Omits unset optional fields from the serialized JSON")
    void omitsNullFieldsInJson() throws Exception {
        SubtitleMetadataDTO dto = SubtitleMetadataDTO.builder()
                .id("subtitle-1").url("https://example.com/subtitle.vtt")
                .language("en").mimeType("text/vtt").build(); // no languageName/kind/format

        String json = objectMapper.writeValueAsString(dto);

        assertThat(json).doesNotContain("\"languageName\"", "\"kind\"", "\"format\"");
    }

    @Test
    @DisplayName("Round-trips every field through serialize/deserialize unchanged")
    void roundTripPreservesAllFields() throws Exception {
        SubtitleMetadataDTO original = validBuilder().format("VTT").build();

        SubtitleMetadataDTO restored = objectMapper.readValue(
                objectMapper.writeValueAsString(original), SubtitleMetadataDTO.class);

        assertThat(restored.getId()).isEqualTo(original.getId());
        assertThat(restored.getUrl()).isEqualTo(original.getUrl());
        assertThat(restored.getLanguage()).isEqualTo(original.getLanguage());
        assertThat(restored.getLanguageName()).isEqualTo(original.getLanguageName());
        assertThat(restored.getMimeType()).isEqualTo(original.getMimeType());
        assertThat(restored.getKind()).isEqualTo(original.getKind());
        assertThat(restored.getBandwidth()).isEqualTo(original.getBandwidth());
        assertThat(restored.getFormat()).isEqualTo(original.getFormat());
    }

    // ── toString ─────────────────────────────────────────────────────────

    @Test
    @DisplayName("toString includes the key identifying fields")
    void toStringIncludesKeyFields() {
        String result = validBuilder().build().toString();

        assertThat(result).contains("subtitle-1", "en", "English", "text/vtt", "subtitles");
    }
}