# Logging Configuration
logging.level.root=INFO
logging.level.org.example.api=INFO
logging.level.org.schabi.newpipe=WARN

logging.pattern.console=%d{HH:mm:ss:SSS} %-5level [%X{requestId:-}] %logger{36} - %msg%n

# Jackson Configuration
spring.jackson.serialization.indent-output=true

# Expose health endpoint
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always