package org.example.api.service;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.schabi.newpipe.extractor.MediaFormat;
import org.schabi.newpipe.extractor.services.youtube.ItagItem;
import org.schabi.newpipe.extractor.stream.AudioStream;
import org.schabi.newpipe.extractor.stream.SubtitlesStream;
import org.schabi.newpipe.extractor.stream.VideoStream;

import java.util.Collections;
import java.util.List;
import java.util.Locale;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Unit tests for StreamSelectionService (previously untested — the largest
 * block of pure selection logic in the service layer).
 *
 * <p>Fixtures are real NewPipe stream objects built via their Builders,
 * not mocks — the same reasoning as elsewhere in this suite: several
 * NewPipe getters are final and, more importantly, the service reads
 * {@code getItagItem().id} as a direct field access, which no mock can
 * fake. Real ItagItems make every code path honest.</p>
 */
@DisplayName("StreamSelectionService Tests")
class StreamSelectionServiceTest {

    private StreamSelectionService service;

    @BeforeEach
    void setUp() {
        service = new StreamSelectionService();
    }

    // ── Fixture factories ────────────────────────────────────────────────

    private static VideoStream videoStream(String id, String resolution, int bitrate) {
        ItagItem itagItem = new ItagItem(299, ItagItem.ItagType.VIDEO_ONLY,
                MediaFormat.MPEG_4, resolution, 30);
        itagItem.setBitrate(bitrate);
        return new VideoStream.Builder()
                .setId(id)
                .setContent("https://example.com/" + id, true)
                .setMediaFormat(MediaFormat.MPEG_4)
                .setIsVideoOnly(true)
                .setResolution(resolution)
                .setItagItem(itagItem)
                .build();
    }

    private static AudioStream audioStream(String id, int itagId, MediaFormat format,
                                           int bitrate, Locale locale, String trackId) {
        ItagItem itagItem = new ItagItem(itagId, ItagItem.ItagType.AUDIO, format, bitrate);
        itagItem.setBitrate(bitrate);
        AudioStream.Builder builder = new AudioStream.Builder()
                .setId(id)
                .setContent("https://example.com/" + id, true)
                .setMediaFormat(format)
                .setAverageBitrate(bitrate)
                .setItagItem(itagItem);
        if (locale != null) {
            builder.setAudioLocale(locale);
        }
        if (trackId != null) {
            builder.setAudioTrackId(trackId);
        }
        return builder.build();
    }

    private static SubtitlesStream subtitle(String languageCode, MediaFormat format,
                                            boolean autoGenerated) {
        // SubtitlesStream.Builder.build() declares NewPipe's checked
        // ParsingException (locale derivation from the language code).
        // A fixture failing to build is a test bug, not a test outcome,
        // so rethrow unchecked and keep the call sites clean.
        try {
            return new SubtitlesStream.Builder()
                    .setContent("https://example.com/" + languageCode + "." + format.getSuffix(), true)
                    .setMediaFormat(format)
                    .setLanguageCode(languageCode)
                    .setAutoGenerated(autoGenerated)
                    .build();
        } catch (Exception e) {
            throw new AssertionError("Failed to build subtitle fixture for language: " + languageCode, e);
        }
    }

    // ── Null/empty guards (all three selectors) ──────────────────────────

    @Test
    @DisplayName("All selectors return an empty list for null or empty input")
    void allSelectors_returnEmptyForNullOrEmptyInput() {
        assertThat(service.selectVideoStreams(null)).isEmpty();
        assertThat(service.selectVideoStreams(Collections.emptyList())).isEmpty();
        assertThat(service.selectAudioStreams(null)).isEmpty();
        assertThat(service.selectAudioStreams(Collections.emptyList())).isEmpty();
        assertThat(service.selectSubtitles(null)).isEmpty();
        assertThat(service.selectSubtitles(Collections.emptyList())).isEmpty();
    }

    // ── Video selection ──────────────────────────────────────────────────

    @Nested
    @DisplayName("selectVideoStreams")
    class VideoSelectionTests {

        @Test
        @DisplayName("Selects one stream per quality level (first occurrence), sorted highest quality first")
        void selectsOnePerQualityLevel_sortedHighestFirst() {
            VideoStream firstOf720 = videoStream("720-a", "720p", 1_200_000);
            List<VideoStream> selected = service.selectVideoStreams(List.of(
                    firstOf720,
                    videoStream("360", "360p", 400_000),
                    videoStream("1080", "1080p", 3_400_000),
                    videoStream("720-b", "720p", 1_100_000)));

            assertThat(selected).extracting(VideoStream::getResolution)
                    .containsExactly("1080p", "720p", "360p");
            // The duplicate resolution keeps the FIRST occurrence
            assertThat(selected).extracting(VideoStream::getId)
                    .contains("720-a")
                    .doesNotContain("720-b");
        }

        @Test
        @DisplayName("Caps selection at six quality levels, keeping the highest six")
        void capsAtSixQualityLevels() {
            List<VideoStream> selected = service.selectVideoStreams(List.of(
                    videoStream("144", "144p", 100_000),
                    videoStream("240", "240p", 200_000),
                    videoStream("360", "360p", 400_000),
                    videoStream("480", "480p", 700_000),
                    videoStream("720", "720p", 1_200_000),
                    videoStream("1080", "1080p", 3_400_000),
                    videoStream("1440", "1440p", 8_000_000),
                    videoStream("2160", "2160p", 16_000_000)));

            assertThat(selected).extracting(VideoStream::getResolution)
                    .containsExactly("2160p", "1440p", "1080p", "720p", "480p", "360p");
        }

        @Test
        @DisplayName("Backfills by highest bitrate when fewer than three known quality levels exist")
        void backfillsByBitrate_whenTooFewKnownQualities() {
            // One recognised quality plus three non-standard resolution labels:
            // the second pass must top up to three streams by bitrate.
            List<VideoStream> selected = service.selectVideoStreams(List.of(
                    videoStream("known-720", "720p", 1_200_000),
                    videoStream("odd-low", "8K", 1_000_000),
                    videoStream("odd-high", "premium", 9_000_000),
                    videoStream("odd-mid", "5K", 5_000_000)));

            assertThat(selected).hasSize(3);
            // Known quality sorts first; unknown resolutions (not in the
            // quality table) sort last, in bitrate-descending backfill order.
            assertThat(selected).extracting(VideoStream::getId)
                    .containsExactly("known-720", "odd-high", "odd-mid");
        }
    }

    // ── Audio selection ──────────────────────────────────────────────────

    @Nested
    @DisplayName("selectAudioStreams")
    class AudioSelectionTests {

        @Test
        @DisplayName("Selects one stream per language, choosing by itag preference within a language")
        void selectsOnePerLanguage_byItagPreference() {
            // en has itags 251 and 140; 140 ranks higher in the preference
            // list despite 251's higher bitrate.
            List<AudioStream> selected = service.selectAudioStreams(List.of(
                    audioStream("en-webm", 251, MediaFormat.WEBMA, 160_000, Locale.forLanguageTag("en"), null),
                    audioStream("en-m4a", 140, MediaFormat.M4A, 128_000, Locale.forLanguageTag("en"), null),
                    audioStream("es-m4a", 140, MediaFormat.M4A, 128_000, Locale.forLanguageTag("es"), null)));

            assertThat(selected).hasSize(2);
            assertThat(selected).extracting(AudioStream::getId)
                    .containsExactly("en-m4a", "es-m4a");
        }

        @Test
        @DisplayName("Orders languages und → en → others alphabetically, resolving language from locale, track id, or neither")
        void ordersLanguages_resolvingFromLocaleTrackIdOrNeither() {
            List<AudioStream> selected = service.selectAudioStreams(List.of(
                    audioStream("spanish", 140, MediaFormat.M4A, 128_000, Locale.forLanguageTag("es"), null),
                    audioStream("english", 140, MediaFormat.M4A, 128_000, Locale.forLanguageTag("en"), null),
                    // No locale: language comes from the track id, normalised
                    // (underscores to dashes, lowercased): "DE_de" -> "de-de"
                    audioStream("german-by-track-id", 140, MediaFormat.M4A, 128_000, null, "DE_de"),
                    // Neither locale nor track id -> "und", which sorts first
                    audioStream("original", 140, MediaFormat.M4A, 128_000, null, null)));

            assertThat(selected).extracting(AudioStream::getId)
                    .containsExactly("original", "english", "german-by-track-id", "spanish");
        }

        @Test
        @DisplayName("Falls back to the best M4A by bitrate when no preferred itag matches, then to highest bitrate overall")
        void fallsBackToM4aThenHighestBitrate() {
            // itags 300/301/302 are not in the preference list.
            // en: m4a should win over the higher-bitrate webm.
            // es: no m4a present -> plain highest bitrate wins.
            List<AudioStream> selected = service.selectAudioStreams(List.of(
                    audioStream("en-webm-high", 301, MediaFormat.WEBMA, 160_000, Locale.forLanguageTag("en"), null),
                    audioStream("en-m4a-low", 300, MediaFormat.M4A, 128_000, Locale.forLanguageTag("en"), null),
                    audioStream("es-webm-low", 302, MediaFormat.WEBMA, 70_000, Locale.forLanguageTag("es"), null),
                    audioStream("es-webm-high", 301, MediaFormat.WEBMA, 160_000, Locale.forLanguageTag("es"), null)));

            assertThat(selected).extracting(AudioStream::getId)
                    .containsExactly("en-m4a-low", "es-webm-high");
        }
    }

    // ── Subtitle selection ───────────────────────────────────────────────

    @Nested
    @DisplayName("selectSubtitles")
    class SubtitleSelectionTests {

        @Test
        @DisplayName("Keeps only the highest-preference format tier that has any matches")
        void keepsOnlyHighestPreferredFormatTier() {
            // NOTE: this documents current behaviour — the format filter is
            // global, not per-language. Because a VTT exists, the TTML-only
            // Spanish track is dropped ENTIRELY rather than falling back to
            // TTML for that language. If that's not intended, the fix
            // belongs in filterSubtitlesByFormat, and this test will flag it.
            List<SubtitlesStream> selected = service.selectSubtitles(List.of(
                    subtitle("en", MediaFormat.VTT, false),
                    subtitle("es", MediaFormat.TTML, false)));

            assertThat(selected).hasSize(1);
            assertThat(selected.get(0).getLocale().toLanguageTag()).isEqualTo("en");
        }

        @Test
        @DisplayName("Deduplicates by language, preferring manual over auto-generated")
        void deduplicatesByLanguage_preferringManual() {
            SubtitlesStream auto = subtitle("en", MediaFormat.VTT, true);
            SubtitlesStream manual = subtitle("en", MediaFormat.VTT, false);

            List<SubtitlesStream> selected = service.selectSubtitles(List.of(auto, manual));

            assertThat(selected).hasSize(1);
            assertThat(selected.get(0).isAutoGenerated()).isFalse();
        }

        @Test
        @DisplayName("Orders subtitle languages en-first then alphabetically")
        void ordersByLanguagePriority() {
            List<SubtitlesStream> selected = service.selectSubtitles(List.of(
                    subtitle("fr", MediaFormat.VTT, false),
                    subtitle("es", MediaFormat.VTT, false),
                    subtitle("en", MediaFormat.VTT, false)));

            assertThat(selected)
                    .extracting(s -> s.getLocale().toLanguageTag())
                    .containsExactly("en", "es", "fr");
        }
    }
}