package org.example.api.service;

import org.junit.jupiter.api.*;
import org.schabi.newpipe.extractor.MediaFormat;
import org.schabi.newpipe.extractor.services.youtube.ItagItem;
import org.schabi.newpipe.extractor.stream.AudioStream;
import org.schabi.newpipe.extractor.stream.DeliveryMethod;
import org.schabi.newpipe.extractor.stream.SubtitlesStream;
import org.schabi.newpipe.extractor.stream.VideoStream;

import java.util.Collections;
import java.util.List;
import java.util.Locale;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Unit tests for StreamSelectionService
 */
@DisplayName("StreamSelectionService Tests")
class StreamSelectionServiceTest {

    private StreamSelectionService service;

    @BeforeEach
    void setUp() {
        service = new StreamSelectionService();
    }

    // ── Fixture factories ────────────────────────────────────────────────

    private static VideoStream videoStream(String id, String resolution, int bitrate) {
        return videoStream(id, resolution, bitrate, DeliveryMethod.PROGRESSIVE_HTTP);
    }

    private static VideoStream videoStream(String id, String resolution, int bitrate,
                                           DeliveryMethod deliveryMethod) {
        ItagItem itagItem = new ItagItem(299, ItagItem.ItagType.VIDEO_ONLY,
                MediaFormat.MPEG_4, resolution, 30);
        itagItem.setBitrate(bitrate);
        return new VideoStream.Builder()
                .setId(id)
                .setContent("https://example.com/" + id, true)
                .setMediaFormat(MediaFormat.MPEG_4)
                .setIsVideoOnly(true)
                .setResolution(resolution)
                .setDeliveryMethod(deliveryMethod)
                .setItagItem(itagItem)
                .build();
    }

    private static final int FIXTURE_AUDIO_ITAG = 140;

    private static AudioStream audioStream(String id, MediaFormat format, int bitrate,
                                           Locale locale, String trackId) {
        return audioStream(id, format, bitrate, locale, trackId, DeliveryMethod.PROGRESSIVE_HTTP);
    }

    private static AudioStream audioStream(String id, MediaFormat format, int bitrate,
                                           Locale locale, String trackId,
                                           DeliveryMethod deliveryMethod) {
        ItagItem itagItem = new ItagItem(FIXTURE_AUDIO_ITAG, ItagItem.ItagType.AUDIO, format, bitrate);
        itagItem.setBitrate(bitrate);
        AudioStream.Builder builder = new AudioStream.Builder()
                .setId(id)
                .setContent("https://example.com/" + id, true)
                .setMediaFormat(format)
                .setAverageBitrate(bitrate)
                .setDeliveryMethod(deliveryMethod)
                .setItagItem(itagItem);
        if (locale != null) {
            builder.setAudioLocale(locale);
        }
        if (trackId != null) {
            builder.setAudioTrackId(trackId);
        }
        return builder.build();
    }

    private static SubtitlesStream subtitle(String languageCode, MediaFormat format,
                                            boolean autoGenerated) {
        try {
            return new SubtitlesStream.Builder()
                    .setContent("https://example.com/" + languageCode + "." + format.getSuffix(), true)
                    .setMediaFormat(format)
                    .setLanguageCode(languageCode)
                    .setAutoGenerated(autoGenerated)
                    .build();
        } catch (Exception e) {
            throw new AssertionError("Failed to build subtitle fixture for language: " + languageCode, e);
        }
    }

    // ── Null/empty guards (all three selectors) ──────────────────────────

    @Test
    @DisplayName("All selectors return an empty list for null or empty input")
    void allSelectors_returnEmptyForNullOrEmptyInput() {
        assertThat(service.selectVideoStreams(null)).isEmpty();
        assertThat(service.selectVideoStreams(Collections.emptyList())).isEmpty();
        assertThat(service.selectAudioStreams(null)).isEmpty();
        assertThat(service.selectAudioStreams(Collections.emptyList())).isEmpty();
        assertThat(service.selectSubtitles(null)).isEmpty();
        assertThat(service.selectSubtitles(Collections.emptyList())).isEmpty();
    }

    // ── Video selection ──────────────────────────────────────────────────

    @Nested
    @DisplayName("selectVideoStreams")
    class VideoSelectionTests {

        @Test
        @DisplayName("Selects one stream per quality level (first occurrence), sorted highest quality first")
        void selectsOnePerQualityLevel_sortedHighestFirst() {
            VideoStream firstOf720 = videoStream("720-a", "720p", 1_200_000);
            List<VideoStream> selected = service.selectVideoStreams(List.of(
                    firstOf720,
                    videoStream("360", "360p", 400_000),
                    videoStream("1080", "1080p", 3_400_000),
                    videoStream("720-b", "720p", 1_100_000)));

            assertThat(selected).extracting(VideoStream::getResolution)
                    .containsExactly("1080p", "720p", "360p");
            // The duplicate resolution keeps the FIRST occurrence
            assertThat(selected).extracting(VideoStream::getId)
                    .contains("720-a")
                    .doesNotContain("720-b");
        }

        @Test
        @DisplayName("Caps selection at six quality levels, keeping the highest six")
        void capsAtSixQualityLevels() {
            List<VideoStream> selected = service.selectVideoStreams(List.of(
                    videoStream("144", "144p", 100_000),
                    videoStream("240", "240p", 200_000),
                    videoStream("360", "360p", 400_000),
                    videoStream("480", "480p", 700_000),
                    videoStream("720", "720p", 1_200_000),
                    videoStream("1080", "1080p", 3_400_000),
                    videoStream("1440", "1440p", 8_000_000),
                    videoStream("2160", "2160p", 16_000_000)));

            assertThat(selected).extracting(VideoStream::getResolution)
                    .containsExactly("2160p", "1440p", "1080p", "720p", "480p", "360p");
        }

        @Test
        @DisplayName("Backfills by highest bitrate when fewer than three known quality levels exist")
        void backfillsByBitrate_whenTooFewKnownQualities() {
            List<VideoStream> selected = service.selectVideoStreams(List.of(
                    videoStream("known-720", "720p", 1_200_000),
                    videoStream("odd-low", "8K", 1_000_000),
                    videoStream("odd-high", "premium", 9_000_000),
                    videoStream("odd-mid", "5K", 5_000_000)));

            assertThat(selected).hasSize(3);
            assertThat(selected).extracting(VideoStream::getId)
                    .containsExactly("known-720", "odd-high", "odd-mid");
        }

        @Test
        @DisplayName("Skips streams that are not delivered over progressive HTTP")
        void skipsNonProgressiveDeliveryStreams() {
            List<VideoStream> selected = service.selectVideoStreams(List.of(
                    videoStream("dash-1080", "1080p", 3_400_000, DeliveryMethod.DASH),
                    videoStream("http-720", "720p", 1_200_000)));

            // The DASH stream is the higher quality; it is still excluded,
            // and the backfill cannot resurrect it.
            assertThat(selected).extracting(VideoStream::getId)
                    .containsExactly("http-720");
        }

        @Test
        @DisplayName("Returns empty when no stream uses a supported delivery method")
        void returnsEmptyWhenNoProgressiveStreams() {
            List<VideoStream> selected = service.selectVideoStreams(List.of(
                    videoStream("dash-1080", "1080p", 3_400_000, DeliveryMethod.DASH),
                    videoStream("hls-720", "720p", 1_200_000, DeliveryMethod.HLS)));

            assertThat(selected).isEmpty();
        }
    }

    // ── Audio selection ──────────────────────────────────────────────────

    @Nested
    @DisplayName("selectAudioStreams")
    class AudioSelectionTests {

        @Test
        @DisplayName("Selects one stream per language, choosing by codec preference within a language")
        void selectsOnePerLanguage_byCodecPreference() {
            // en has a WebM at 160k and an M4A at 128k. M4A ranks in the
            // codec preference list and WebM does not, so the lower-bitrate
            // M4A wins — codec rank is applied before bitrate.
            List<AudioStream> selected = service.selectAudioStreams(List.of(
                    audioStream("en-webm", MediaFormat.WEBMA, 160_000, Locale.forLanguageTag("en"), null),
                    audioStream("en-m4a", MediaFormat.M4A, 128_000, Locale.forLanguageTag("en"), null),
                    audioStream("es-m4a", MediaFormat.M4A, 128_000, Locale.forLanguageTag("es"), null)));

            assertThat(selected).hasSize(2);
            assertThat(selected).extracting(AudioStream::getId)
                    .containsExactly("en-m4a", "es-m4a");
        }

        @Test
        @DisplayName("Orders languages und → en → others @Test\n" +
                "        @DisplayName(\"Selects one stream per language, choosing by itag preference within a language\")\n" +
                "        void  alphabetically, resolving language from locale, track id, or neither")
        void ordersLanguages_resolvingFromLocaleTrackIdOrNeither() {
            List<AudioStream> selected = service.selectAudioStreams(List.of(
                    audioStream("spanish", MediaFormat.M4A, 128_000, Locale.forLanguageTag("es"), null),
                    audioStream("english", MediaFormat.M4A, 128_000, Locale.forLanguageTag("en"), null),
                    audioStream("german-by-track-id", MediaFormat.M4A, 128_000, null, "DE_de"),
                    audioStream("original", MediaFormat.M4A, 128_000, null, null)));

            assertThat(selected).extracting(AudioStream::getId)
                    .containsExactly("original", "english", "german-by-track-id", "spanish");
        }

        @Test
        @DisplayName("Falls back to bitrate when no codec in the group is ranked")
        void fallsBackToBitrateWhenNoCodecRanked() {
            // en: M4A ranks, WebM does not, so codec rank decides.
            // es: neither WebM ranks, so the tie-break on bitrate decides.
            List<AudioStream> selected = service.selectAudioStreams(List.of(
                    audioStream("en-webm-high", MediaFormat.WEBMA, 160_000, Locale.forLanguageTag("en"), null),
                    audioStream("en-m4a-low", MediaFormat.M4A, 128_000, Locale.forLanguageTag("en"), null),
                    audioStream("es-webm-low", MediaFormat.WEBMA, 70_000, Locale.forLanguageTag("es"), null),
                    audioStream("es-webm-high", MediaFormat.WEBMA, 160_000, Locale.forLanguageTag("es"), null)));

            assertThat(selected).extracting(AudioStream::getId)
                    .containsExactly("en-m4a-low", "es-webm-high");
        }

        @Test
        @DisplayName("Filters by delivery method before codec ranking, dropping languages left with nothing")
        void skipsNonProgressiveDeliveryStreams() {
            List<AudioStream> selected = service.selectAudioStreams(List.of(
                    audioStream("en-dash-m4a", MediaFormat.M4A, 256_000,
                            Locale.forLanguageTag("en"), null, DeliveryMethod.DASH),
                    audioStream("en-http-webm", MediaFormat.WEBMA, 160_000,
                            Locale.forLanguageTag("en"), null),
                    audioStream("es-dash-m4a", MediaFormat.M4A, 128_000,
                            Locale.forLanguageTag("es"), null, DeliveryMethod.DASH)));

            // The DASH M4A would out-rank the WebM on codec, so its absence
            // proves the filter runs first; Spanish has no usable stream at
            // all and drops out of the result entirely.
            assertThat(selected).extracting(AudioStream::getId)
                    .containsExactly("en-http-webm");
        }
    }

    // ── Subtitle selection ───────────────────────────────────────────────

    @Nested
    @DisplayName("selectSubtitles")
    class SubtitleSelectionTests {

        @Test
        @DisplayName("Applies the format cascade within each language, not across the whole list")
        void appliesFormatCascadePerLanguage() {
            List<SubtitlesStream> selected = service.selectSubtitles(List.of(
                    subtitle("en", MediaFormat.VTT, false),
                    subtitle("es", MediaFormat.TTML, false)));

            assertThat(selected).hasSize(2);
            assertThat(selected)
                    .extracting(s -> s.getLocale().toLanguageTag())
                    .containsExactly("en", "es");
            // Spanish keeps TTML rather than being dropped because English had VTT
            assertThat(selected)
                    .extracting(s -> {
                        Assertions.assertNotNull(s.getFormat());
                        return s.getFormat().getSuffix();
                    })
                    .containsExactly("vtt", "ttml");
        }

        @Test
        @DisplayName("Within a language, the highest-ranked available format still wins")
        void prefersHigherRankedFormatWithinALanguage() {
            List<SubtitlesStream> selected = service.selectSubtitles(List.of(
                    subtitle("en", MediaFormat.TTML, false),
                    subtitle("en", MediaFormat.VTT, false),
                    subtitle("es", MediaFormat.TTML, false)));

            assertThat(selected)
                    .extracting(s -> {
                        Assertions.assertNotNull(s.getFormat());
                        return s.getFormat().getSuffix();
                    })
                    .containsExactly("vtt", "ttml");
        }

        @Test
        @DisplayName("Deduplicates by language, preferring manual over auto-generated")
        void deduplicatesByLanguage_preferringManual() {
            SubtitlesStream auto = subtitle("en", MediaFormat.VTT, true);
            SubtitlesStream manual = subtitle("en", MediaFormat.VTT, false);

            List<SubtitlesStream> selected = service.selectSubtitles(List.of(auto, manual));

            assertThat(selected).hasSize(1);
            assertThat(selected.getFirst().isAutoGenerated()).isFalse();
        }

        @Test
        @DisplayName("Orders subtitle languages en-first then alphabetically")
        void ordersByLanguagePriority() {
            List<SubtitlesStream> selected = service.selectSubtitles(List.of(
                    subtitle("fr", MediaFormat.VTT, false),
                    subtitle("es", MediaFormat.VTT, false),
                    subtitle("en", MediaFormat.VTT, false)));

            assertThat(selected)
                    .extracting(s -> s.getLocale().toLanguageTag())
                    .containsExactly("en", "es", "fr");
        }
    }
}