package org.example.api.dto.dash;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.schabi.newpipe.extractor.stream.SubtitlesStream;
import org.schabi.newpipe.extractor.MediaFormat;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;

/**
 * Data Transfer Object representing metadata for a subtitle track in a DASH manifest.
 * Contains information about subtitle language, format, and location.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class SubtitleMetadataDTO {

    /**
     * Unique identifier for this subtitle representation in the DASH manifest.
     */
    @NotBlank(message = "Subtitle ID cannot be blank")
    @JsonProperty("id")
    private String id;

    /**
     * Direct URL to the subtitle content.
     */
    @NotBlank(message = "Subtitle URL cannot be blank")
    @JsonProperty("url")
    private String url;

    /**
     * Language code for this subtitle track (e.g., "en", "es", "fr").
     */
    @NotBlank(message = "Subtitle language cannot be blank")
    @JsonProperty("language")
    private String language;

    /**
     * Human-readable language name (e.g., "English", "Spanish", "French").
     */
    @JsonProperty("languageName")
    private String languageName;

    /**
     * MIME type of the subtitle format (e.g., "application/ttml+xml", "text/vtt").
     */
    @NotBlank(message = "Subtitle MIME type cannot be blank")
    @JsonProperty("mimeType")
    private String mimeType;

    /**
     * Kind of subtitle track (e.g., "subtitles", "captions", "asr" for auto-generated).
     */
    @JsonProperty("kind")
    private String kind;

    /**
     * Bandwidth estimate for subtitle stream (typically low, default 256 bits/sec).
     */
    @Min(value = 1, message = "Bandwidth must be at least 1")
    @JsonProperty("bandwidth")
    private int bandwidth;

    /**
     * Format code from the extractor (optional, for debugging).
     */
    @JsonProperty("format")
    private String format;

    // Constructors

    /**
     * Default constructor for Jackson deserialization.
     */
    public SubtitleMetadataDTO() {
        this.bandwidth = 256; // Default bandwidth for text streams
    }

    /**
     * Full constructor for creating a SubtitleMetadataDTO with all fields.
     */
    public SubtitleMetadataDTO(String id, String url, String language, String languageName,
                               String mimeType, String kind, int bandwidth, String format) {
        this.id = id;
        this.url = url;
        this.language = language;
        this.languageName = languageName;
        this.mimeType = mimeType;
        this.kind = kind;
        this.bandwidth = bandwidth > 0 ? bandwidth : 256;
        this.format = format;
    }

    // Static Factory Method

    /**
     * Creates a SubtitleMetadataDTO from a NewPipe SubtitlesStream object.
     *
     * @param stream The SubtitlesStream from NewPipe extractor
     * @param index  The index used to generate a unique ID
     * @return A new SubtitleMetadataDTO instance
     */
    public static SubtitleMetadataDTO from(SubtitlesStream stream, int index) {
        if (stream == null) {
            throw new IllegalArgumentException("SubtitlesStream cannot be null");
        }

        SubtitleMetadataDTO dto = new SubtitleMetadataDTO();
        dto.setId("subtitle-" + index);
        dto.setUrl(stream.getContent());

        // Handle language information
        String lang = stream.getLocale() != null ?
                stream.getLocale().getLanguage() : "en";
        dto.setLanguage(lang);
        dto.setLanguageName(stream.getDisplayLanguageName() != null ?
                stream.getDisplayLanguageName() :
                getLanguageDisplayName(lang));

        // Determine MIME type from format
        String mimeType = inferMimeTypeFromFormat(stream.getFormat());
        dto.setMimeType(mimeType);

        // Set subtitle kind (asr for auto-generated, subtitles otherwise)
        dto.setKind(stream.isAutoGenerated() ? "asr" : "subtitles");

        dto.setBandwidth(256); // Standard bandwidth for text streams
        dto.setFormat(stream.getFormat() != null ? stream.getFormat().getName() : null);

        return dto;
    }

    /**
     * Infers MIME type from subtitle format.
     *
     * @param format The subtitle format
     * @return Appropriate MIME type
     */
    private static String inferMimeTypeFromFormat(MediaFormat format) {
        if (format == null) {
            return "application/ttml+xml"; // Default to TTML
        }

        return switch (format) {
            case VTT -> "text/vtt";
            case SRT -> "application/x-subrip";
            default -> "application/ttml+xml";
        };
    }

    /**
     * Helper method to get display name for language code.
     * This is a simple implementation - can be expanded with more language mappings.
     *
     * @param languageCode The ISO language code
     * @return Human-readable language name
     */
    private static String getLanguageDisplayName(String languageCode) {
        if (languageCode == null || languageCode.isEmpty()) {
            return "Unknown";
        }

        return switch (languageCode.toLowerCase()) {
            case "en" -> "English";
            case "es" -> "Spanish";
            case "fr" -> "French";
            case "de" -> "German";
            case "it" -> "Italian";
            case "pt" -> "Portuguese";
            case "ru" -> "Russian";
            case "ja" -> "Japanese";
            case "ko" -> "Korean";
            case "zh" -> "Chinese";
            case "ar" -> "Arabic";
            case "hi" -> "Hindi";
            case "nl" -> "Dutch";
            case "pl" -> "Polish";
            case "tr" -> "Turkish";
            case "und" -> "Unknown";
            default -> languageCode.toUpperCase();
        };
    }

    // Builder Pattern

    /**
     * Creates a new Builder for constructing SubtitleMetadataDTO instances.
     *
     * @return A new Builder instance
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builder class for fluent construction of SubtitleMetadataDTO instances.
     */
    public static class Builder {
        private String id;
        private String url;
        private String language;
        private String languageName;
        private String mimeType;
        private String kind;
        private int bandwidth = 256;
        private String format;

        public Builder id(String id) {
            this.id = id;
            return this;
        }

        public Builder url(String url) {
            this.url = url;
            return this;
        }

        public Builder language(String language) {
            this.language = language;
            return this;
        }

        public Builder languageName(String languageName) {
            this.languageName = languageName;
            return this;
        }

        public Builder mimeType(String mimeType) {
            this.mimeType = mimeType;
            return this;
        }

        public Builder kind(String kind) {
            this.kind = kind;
            return this;
        }

        public Builder bandwidth(int bandwidth) {
            this.bandwidth = bandwidth;
            return this;
        }

        public Builder format(String format) {
            this.format = format;
            return this;
        }

        public SubtitleMetadataDTO build() {
            return new SubtitleMetadataDTO(id, url, language, languageName,
                    mimeType, kind, bandwidth, format);
        }
    }

    // Getters and Setters

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getLanguageName() {
        return languageName;
    }

    public void setLanguageName(String languageName) {
        this.languageName = languageName;
    }

    public String getMimeType() {
        return mimeType;
    }

    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    public String getKind() {
        return kind;
    }

    public void setKind(String kind) {
        this.kind = kind;
    }

    public int getBandwidth() {
        return bandwidth;
    }

    public void setBandwidth(int bandwidth) {
        this.bandwidth = bandwidth;
    }

    public String getFormat() {
        return format;
    }

    public void setFormat(String format) {
        this.format = format;
    }

    @Override
    public String toString() {
        return "SubtitleMetadataDTO{id='%s', language='%s', languageName='%s', mimeType='%s', kind='%s'}".formatted(id, language, languageName, mimeType, kind);
    }
}