/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.api;

import org.schabi.newpipe.extractor.NewPipe;
import org.schabi.newpipe.extractor.localization.Localization;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {
    private static final Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {

        DownloaderImpl downloader = DownloaderImpl.init(null);
        logger.info("DownloaderImpl initialized: {}", downloader);

        NewPipe.init(downloader, new Localization("en", "GB"));
        logger.info("NewPipe initialized successfully");

        SpringApplication.run(App.class, args);
    }
}
